name: talos1
description: "A new Flutter project."
publish_to: 'none' 

version: '2.1.1'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  signature: ^4.0.2
  flutter_screenutil: ^5.0.0+2  # Adicionada a nova dependência
  shared_preferences: ^2.0.15
  geolocator: ^7.6.0
  geocoding: ^2.1.1
  device_info: ^2.0.3
  intl: ^0.17.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.4+1
  camera: ^0.9.4+5
  blue_thermal_printer: ^1.2.3
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  file_picker: ^4.2.5
  excel: 4.0.2
  permission_handler: ^8.1.4
  flutter_masked_text2: ^0.9.1
  connectivity: ^3.0.6
  image: ^3.0.1
  dio: ^4.0.0
  url_launcher: ^6.2.6
  screenshot: ^2.1.0
  pdf: ^3.5.0
  printing: ^5.5.0
  charset_converter: ^2.0.0
  gallery_saver: ^2.0.1
  google_mlkit_text_recognition: ^0.11.0
  google_maps_flutter: ^2.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - imagens/

fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf